# Generated by Django 3.2 on 2021-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aozora',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ind', models.CharField(blank=True, db_column='IND', max_length=10, null=True)),
                ('author', models.CharField(blank=True, db_column='AUTHOR', max_length=100, null=True)),
                ('book', models.CharField(blank=True, db_column='BOOK', max_length=300, null=True)),
                ('cmt', models.CharField(blank=True, db_column='CMT', max_length=300, null=True)),
            ],
            options={
                'db_table': 'aozora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'app1_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inputdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, db_column='TEXT', max_length=100, null=True)),
                ('insert_date', models.DateTimeField(blank=True, db_column='INSERT_DATE', null=True)),
            ],
            options={
                'db_table': 'inputdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iseki',
            fields=[
                ('ledger_id', models.CharField(db_column='LEDGER_ID', max_length=10, primary_key=True, serialize=False)),
                ('manage_id', models.CharField(db_column='MANAGE_ID', max_length=10)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=1000, null=True)),
                ('buillding_name', models.CharField(blank=True, db_column='BUILLDING_NAME', max_length=100, null=True)),
                ('cultural_kind', models.CharField(blank=True, db_column='CULTURAL_KIND', max_length=100, null=True)),
                ('kind1', models.CharField(blank=True, db_column='KIND1', max_length=100, null=True)),
                ('kind2', models.CharField(blank=True, db_column='KIND2', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=10, null=True)),
                ('age', models.CharField(blank=True, db_column='AGE', max_length=100, null=True)),
                ('imp_clt_dgn_ymd', models.CharField(blank=True, db_column='IMP_CLT_DGN_YMD', max_length=10, null=True)),
                ('nat_trs_dgn_ymd', models.CharField(blank=True, db_column='NAT_TRS_DGN_YMD', max_length=10, null=True)),
                ('prefectures', models.CharField(blank=True, db_column='PREFECTURES', max_length=10, null=True)),
                ('location', models.CharField(blank=True, db_column='LOCATION', max_length=100, null=True)),
                ('storage_name', models.CharField(blank=True, db_column='STORAGE_NAME', max_length=100, null=True)),
                ('owner', models.CharField(blank=True, db_column='OWNER', max_length=100, null=True)),
                ('manager', models.CharField(blank=True, db_column='MANAGER', max_length=100, null=True)),
                ('lat', models.CharField(blank=True, db_column='LAT', max_length=100, null=True)),
                ('lon', models.CharField(blank=True, db_column='LON', max_length=100, null=True)),
            ],
            options={
                'db_table': 'iseki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=100, null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=100, null=True)),
                ('realpassword', models.CharField(blank=True, db_column='REALPASSWORD', max_length=100, null=True)),
                ('insert_date', models.DateTimeField(blank=True, db_column='INSERT_DATE', null=True)),
            ],
            options={
                'db_table': 'userdata',
                'managed': False,
            },
        ),
    ]
